# Generated by Django 4.1.1 on 2022-10-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gembaitemitem',
            name='action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gembaitemitem',
            name='answer',
            field=models.CharField(choices=[('OK', 'OK'), ('NK', 'NK')], max_length=30),
        ),
        migrations.AlterField(
            model_name='gembaitemitem',
            name='problem',
            field=models.TextField(blank=True, null=True),
        ),
    ]
