# Generated by Django 4.1.1 on 2022-10-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0003_alter_gembaitemitem_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gembaitemitem',
            name='action',
            field=models.TextField(blank=True, null=True),
        ),
    ]
