# Generated by Django 4.1.1 on 2022-10-21 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='Default User', max_length=50)),
                ('updated_by', models.CharField(default='Default User', max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=50, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('restored_by', models.CharField(blank=True, max_length=50, null=True)),
                ('reference', models.CharField(default='REF', max_length=100)),
                ('visit_date', models.DateField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.employee', to_field='matricule')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.workshop')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VmsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField()),
                ('condition_type', models.CharField(choices=[('PP', 'PP'), ('AD', 'AD'), ('CD', 'CD')], max_length=10)),
                ('dialogue_answer', models.TextField(blank=True, null=True)),
                ('action_type', models.CharField(blank=True, choices=[('IMM', 'IMM'), ('DIF', 'DIF')], max_length=10, null=True)),
                ('action', models.TextField(blank=True, null=True)),
                ('manager', models.CharField(blank=True, max_length=30, null=True)),
                ('delay', models.DateField(blank=True, null=True)),
                ('vms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vms.vms')),
            ],
        ),
    ]
