# Generated by Django 4.1.1 on 2022-10-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vms',
            name='manager',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
