# Generated by Django 4.1.1 on 2022-10-09 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0002_vms_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vms',
            name='action',
        ),
        migrations.RemoveField(
            model_name='vms',
            name='action_type',
        ),
        migrations.RemoveField(
            model_name='vms',
            name='condition_type',
        ),
        migrations.RemoveField(
            model_name='vms',
            name='delay',
        ),
        migrations.RemoveField(
            model_name='vms',
            name='dialogue_answer',
        ),
        migrations.RemoveField(
            model_name='vms',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='vms',
            name='observation',
        ),
        migrations.CreateModel(
            name='VmsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField()),
                ('condition_type', models.CharField(choices=[('PP', 'PP'), ('AD', 'AD'), ('CD', 'CD')], max_length=10)),
                ('dialogue_answer', models.TextField(blank=True, null=True)),
                ('action_type', models.CharField(blank=True, choices=[('IMM', 'IMM'), ('DIF', 'DIF')], max_length=10, null=True)),
                ('action', models.TextField(blank=True, null=True)),
                ('manager', models.CharField(blank=True, max_length=30, null=True)),
                ('delay', models.DateField(blank=True, null=True)),
                ('vms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vms.vms')),
            ],
        ),
    ]
