# Generated by Django 4.0 on 2022-09-08 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('configuration', '0001_initial'),
        ('vmq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vmq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='Default User', max_length=50)),
                ('updated_by', models.CharField(default='Default User', max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=50, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('restored_by', models.CharField(blank=True, max_length=50, null=True)),
                ('reference', models.CharField(default='REF', max_length=100)),
                ('visit_date', models.DateField()),
                ('employee', models.IntegerField(default=1)),
                ('result', models.CharField(choices=[('Conforme', 'Conforme'), ('Non Conforme', 'Non Conforme')], default=('Conforme', 'Conforme'), max_length=30)),
                ('type', models.CharField(choices=[('Application', 'Application'), ('Disposition', 'Disposition')], default=('Application', 'Application'), max_length=30)),
                ('comment', models.TextField(default='Comment')),
                ('items', models.ManyToManyField(to='vmq.Item')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.workshop')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
