# Generated by Django 4.1.1 on 2022-10-14 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_alter_qualification_employee'),
        ('vmq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmq',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.employee', to_field='matricule'),
        ),
    ]
