# Generated by Django 4.1.1 on 2022-09-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='Item name', max_length=100),
        ),
        migrations.AlterField(
            model_name='vmq',
            name='items',
            field=models.ManyToManyField(blank=True, through='vmq.VmqItem', to='vmq.item'),
        ),
        migrations.AlterField(
            model_name='vmqitem',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vmqitem',
            name='result',
            field=models.CharField(choices=[('Conforme', 'Conforme'), ('Non Conforme', 'Non Conforme')], max_length=30),
        ),
        migrations.AlterField(
            model_name='vmqitem',
            name='type',
            field=models.CharField(choices=[('Application', 'Application'), ('Disposition', 'Disposition')], max_length=30),
        ),
    ]
