# Generated by Django 4.1.1 on 2022-11-07 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vmq', '0002_vmqkpi_daterange'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VmqKPI_dateRange',
        ),
    ]
