# Generated by Django 4.1.1 on 2022-09-22 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vmq', '0003_alter_theme_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vmqitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='vmqitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vmqitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vmqitem',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='vmqitem',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='vmqitem',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='vmqitem',
            name='restored_at',
        ),
        migrations.RemoveField(
            model_name='vmqitem',
            name='restored_by',
        ),
        migrations.RemoveField(
            model_name='vmqitem',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='vmqitem',
            name='updated_by',
        ),
    ]
