# Generated by Django 4.1.1 on 2022-10-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmq', '0004_alter_vmqitem_options_remove_vmqitem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmqitem',
            name='action',
            field=models.TextField(default='action'),
            preserve_default=False,
        ),
    ]
