# Generated by Django 4.1.1 on 2022-11-21 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmq', '0004_qualityreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='quality_reference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vmq.qualityreference'),
            preserve_default=False,
        ),
    ]
