# Generated by Django 4.1.1 on 2022-10-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmq', '0005_vmqitem_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmqitem',
            name='action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vmqitem',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
