# Generated by Django 4.1.1 on 2022-11-25 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vmq', '0006_vmqitem_date_vmqitem_defer_immediate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vmq',
            name='reference',
        ),
    ]
