# Generated by Django 4.1.1 on 2022-11-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='division',
            name='location',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
