# Generated by Django 4.1.1 on 2022-10-14 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VMS_Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='Default User', max_length=50)),
                ('updated_by', models.CharField(default='Default User', max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=50, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('restored_by', models.CharField(blank=True, max_length=50, null=True)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('employee1_visited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee1_visited', to='configuration.employee')),
                ('employee2_visited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee2_visited', to='configuration.employee')),
                ('employee_qualified', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_qualified', to='configuration.employee')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
    ]
