# Generated by Django 4.1.1 on 2022-10-14 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_vms_planning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vms_planning',
            name='employee1_visited',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee1_visited', to='configuration.employee', to_field='matricule'),
        ),
        migrations.AlterField(
            model_name='vms_planning',
            name='employee2_visited',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee2_visited', to='configuration.employee', to_field='matricule'),
        ),
        migrations.AlterField(
            model_name='vms_planning',
            name='employee_qualified',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_qualified', to='configuration.employee', to_field='matricule'),
        ),
        migrations.AlterField(
            model_name='vms_planning',
            name='month',
            field=models.CharField(max_length=5),
        ),
    ]
