# Generated by Django 4.1.1 on 2022-10-14 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_alter_vms_planning_employee1_visited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='employee',
            field=models.ForeignKey(db_column='employee', on_delete=django.db.models.deletion.CASCADE, to='configuration.employee', to_field='matricule'),
        ),
    ]
