# Generated by Django 4.1.1 on 2022-10-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_alter_qualification_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='vms_planning',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
