# Generated by Django 4.1.1 on 2022-10-18 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_vms_planning_closed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vms_planning',
            old_name='employee1_visited',
            new_name='employee_visited',
        ),
        migrations.RemoveField(
            model_name='vms_planning',
            name='employee2_visited',
        ),
    ]
